INSERT INTO tips (suggestions, tip)
VALUES ('Pick goals you''re passionate about', 'Make a list of the goals you hope to accomplish. These goals should be meaningful to you and should provide you with a sense of pride and achievement once you meet them. Your goals should be positive and move you forward in your life. It may be helpful to write down improvements you want to make. These can be improvements in your professional role, home-life, relationships or health. Your goals can be large, life-changing goals or smaller goals that provide short-term benefits. Either way, they should make you feel passionate and proud once you complete them.'),
('Make sure your goals are achievable', 'The goals you set should challenge you and be attainable. Set realistic goals for yourself, so you can confidently work toward them knowing you''ll eventually accomplish them. They should also be challenging and somewhat difficult to help you develop your skills and learn new things.'),
('Be specific with your goals','Goal setting should include creating specific goals and specific steps to take to achieve those goals. It''s best to create an overall goal and smaller tasks to help you meet this goal so you can plot a clear plan. Being specific gives you guidance and directions on how to follow through. For example, if your goal is to write more each week, you could make it more specific by saying, `I plan to write three articles a week.` You can then detail your plan to research, write, proofread and publish each article on specific days.'),
('Write these goals down','Listing your goals on paper makes them feel real and helps you remember them. Whether the goals are big or small, write each one down somewhere you''ll regularly see it. Seeing it in writing can be a constant reminder to get to work. You may also enjoy the satisfying feeling of crossing each goal off the list as you complete it.'),     
('Reward yourself when you accomplish a goal','Giving yourself rewards after accomplishing your goals can motivate you to continue achieving more of them. For example, if you''re working toward a challenging goal you''ve almost completed, tell yourself, `If I meet this goal by the end of this week, I''ll go see a movie over the weekend. If I don''t, I''ll stay home and finish it.` Giving yourself a reward gives yourself something positive to look forward to.'),      
( 'Tell others about your goals','It''s easier to hold yourself accountable for your goals if others know about them. Make these goals public by telling friends or colleagues and providing updates on your progress. You can tell a coworker about your goals or encourage your entire team to set workplace goals and ask to hold occasional meetings to check in on everyone''s progress.Knowing others are aware of or are monitoring your progress can encourage you to commit to achieving your goal. It can also make you proud to share your positive results when you accomplish these goals.'),
('Prioritize one goal at a time','Most of your goals should be challenging and take time to accomplish. This is why you set time aside to complete individual tasks for each goal. It''s easier to focus on one item at a time, rather than trying to divide your time between them. This way, you can focus all your energy on one goal to give it your best effort. Once you meet your goal, you''ll know you work your hardest on it, which can provide you a satisfying and worthwhile feeling.'),
('Visualize yourself achieving these goals','There may be days where motivating yourself to meet your goals is challenging, especially if you feel stuck or confused by a certain task. Picture yourself achieving the goal and think about the benefits it''ll provide you when you conquer it.For example, if your goal is to increase your monthly sales quota by 10%, picture your supervisor congratulating you on your achievements or rewarding you with a raise or promotion. This gives you something positive to work toward and can give you the push you need to finish a challenging task.'),   
('Set deadlines for each goal','To ensure you''ll commit to your goals, set clear and realistic deadlines for yourself. After listing specific tasks to complete, you should write out deadlines for each one. For instance, if your overall goal is to type 100 words per minute, your first task can be to practice your typing skills three evenings each week to reach 30 words per minute by the end of the week.You can set a new typing speed deadline each week to hold yourself accountable and allows you to view your progress toward achieving your goals.'),     
('Evaluate each goal you do and don''t accomplish','Return to your previous goals and evaluate the result of each one. It can be helpful to make notes about your experience achieving them along the way. Your notes should explain whether the goal was difficult to meet or what skills or methods you used to accomplish it.Reviewing these notes and your past goals can help you better understand which methods helped you succeed. You can also explain why you didn''t meet certain goals and what you can do better next time to meet them.'),
('Stay positive','There may be moments where you fall short of meeting your goals. It''s important to stay positive during the process and to teach yourself to learn from any mistakes as you keep moving forward to accomplish the next goal. Give yourself positive affirmation by saying, `That''s okay, you''ll meet the next goal.` encourage yourself to continue working toward your goals without giving up.'),
('Create reminders to continue meeting your goals','There may be times when other tasks or projects may appear and shift your focus away from your current goals. Remind yourself each day of these goals by leaving yourself notes in areas you frequently visit to get back on track. You can also use apps on your phone to set regular reminders each week or month to motivate you to follow through with them.'),
('Give yourself an appropriate amount of time to complete them','It''s important to remain realistic with each goal you set by establishing timelines that you''re confident you''ll reach. Set a realistic deadline for your overall goal and then assign smaller due dates for each task. If your tasks end up taking longer to finish than expected, you can adjust your projected dates accordingly.'),
('Remind yourself why you''re setting these goals','Constantly remind yourself why you set the goals and the outlook you''re hoping to see after achieving them. If a goal takes a significant amount of time to complete, it''s important to remind yourself why you set it so you don''t lose sight of what you''re working toward.When you write down the goals you want to achieve, list your reasons for setting each. You can look back on these reasons later when you''re trying to find the motivation to push yourself to complete these goals.'),  
('Assess any possible risks or obstacles','Think about any obstacles that may stand in the way of achieving your goals. Keep these in mind as you set deadlines for yourself. For instance, if you spend the majority of the holiday season away from work and with family, you may not have as much time to accomplish your goals then. Readjust your schedule accordingly to feature realistic deadlines that give you enough time to finish each task.');   
   
      
    
      
   
     
    
      
   
      
   
     
    